# fly.toml app configuration file generated for extreme-startup-player-rtayl397 on 2024-07-25T11:11:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'extreme-startup-player-rtayl397'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8124
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
